### ISSUE TITLE
Callgraph always stored/loaded from the same file

### ISSUE THREAD

**Issue by jedrzejboczar** [t-troebst/perfanno.nvim#18]
When I use `PerfCacheSave <somename>` it always stores the callgraph in the same file `~/.cache/nvim/perfanno/callgraph.1.json`, regardless of the name I use. `PerfCacheLoad <somename>` always loads the same file. The index in `~/.cache/nvim/perfanno/index.json` has all entries pointing to the same file. 
I verified this by adding `vim.notify('Callgraph saved in: ' .. vim.fn.fnamemodify(file, ':p'))` at the end of `M.store_callgraph` and `vim.notify('Loaded callgraph from file: ' .. index[name].file)` in `M.load_callgraph`.

**Comment by t-troebst** [comment]
Thanks for reporting this, this should be fixed now!
