### ISSUE TITLE
How to make this work on Mac?

### ISSUE THREAD

**Issue by jsekerez** [t-troebst/perfanno.nvim#8]
Hi,

My Nvim just became really slow after I upgraded my config, and this looks like the perfect tool to narrow down the problem. Unfortunately I'm on a Mac and I perf doesn't run on it. Are there any plans to make this MacOS-compatible? Or does it work on Mac already? If so, how do I profile my Nvim instance?

**Comment by t-troebst** [comment]
Sorry that I never got back to this. But just for people who see this later: if you want to profile NeoVim you probably just want to use the Lua profiling which doesn't require any external tools. If you want to profile an application on MacOS then you can use `sample` and make it output flamegraph output via https://github.com/brendangregg/FlameGraph/blob/master/stackcollapse-sample.awk.
